const data = [
    {
        title:"COUNTRY",
        info:[
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
        ]
    },
    {
        title:"DELIVERY TIME",
        info:[
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
        ]
    },
    {
        title:"MINIMUM",
        info:[
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
        ]
    },
    {
        title:"VOLUMETRIC WEIGHT",
        info:[
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
        ]
    },
    {
        title:"PRICE (1KG)",
        info:[
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
            {
                icon:"",
                text:""
            },
        ]
    },
]

export default data